# Generated by Django 3.2.4 on 2022-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='prev_checkup',
            field=models.FileField(blank=True, upload_to='prev_checkup'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='prev_consult',
            field=models.FileField(blank=True, upload_to='prev_dt'),
        ),
    ]
