# Generated by Django 4.0.4 on 2022-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_cart_orders_products_delete_checkup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='products/def_post.jpg', null=True, upload_to='products'),
        ),
    ]
