# Generated by Django 3.2.4 on 2022-04-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='date_of_birth',
        ),
    ]
